name: aichatbot
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  auto_route: ^9.3.0+1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  freezed_annotation: ^2.4.4
  shared_preferences: ^2.5.3
  build_runner: ^2.4.13
  equatable: ^2.0.7
  sizer: ^3.0.4
  lottie: ^3.2.0
  intl: ^0.20.2
  json_serializable: ^6.9.0
  freezed: ^2.5.7
  flutter_dotenv: ^5.2.1
  connectivity_plus: ^6.1.4
  dio: ^5.8.0+1
  dio_smart_retry: ^6.0.0
  flutter_native_splash: ^2.4.4
  speech_to_text: ^7.2.0
  flutter_tts: ^4.2.3
  flutter_launcher_icons: ^0.14.4
  flutter_map: ^7.0.2
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  auto_route_generator: ^9.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app/main.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/json/
    - assets/image/
    - assets/app/
    - assets/map/
 
