// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4KJlwsjib582d2traXWZprvTqVTMUEOY',
    appId: '1:1099054987362:web:3ec82633d19e7f3141393b',
    messagingSenderId: '1099054987362',
    projectId: 'chat-app-a9e08',
    authDomain: 'chat-app-a9e08.firebaseapp.com',
    storageBucket: 'chat-app-a9e08.firebasestorage.app',
    measurementId: 'G-DZMN30YC6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPKdA8W1sLTmHOukfAv9IpF6zHfg7I9P0',
    appId: '1:1099054987362:android:32f43614449c056b41393b',
    messagingSenderId: '1099054987362',
    projectId: 'chat-app-a9e08',
    storageBucket: 'chat-app-a9e08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_Myji4QCRoBVK6K0L77r3axZ5Smv6tlE',
    appId: '1:1099054987362:ios:fa9feec521a46ec941393b',
    messagingSenderId: '1099054987362',
    projectId: 'chat-app-a9e08',
    storageBucket: 'chat-app-a9e08.firebasestorage.app',
    iosBundleId: 'com.chat.mn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_Myji4QCRoBVK6K0L77r3axZ5Smv6tlE',
    appId: '1:1099054987362:ios:a64d7bcbc6d25de341393b',
    messagingSenderId: '1099054987362',
    projectId: 'chat-app-a9e08',
    storageBucket: 'chat-app-a9e08.firebasestorage.app',
    iosBundleId: 'com.example.aichatbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4KJlwsjib582d2traXWZprvTqVTMUEOY',
    appId: '1:1099054987362:web:2f8797b96945fa7a41393b',
    messagingSenderId: '1099054987362',
    projectId: 'chat-app-a9e08',
    authDomain: 'chat-app-a9e08.firebaseapp.com',
    storageBucket: 'chat-app-a9e08.firebasestorage.app',
    measurementId: 'G-PWFYMXYMHH',
  );
}
